### ISSUE TITLE
The request must be decorated with 'LazyUploadHttpWebRequestDecorator'

### ISSUE THREAD

**Issue by VordanN** [gsemac/Gsemac.Net.Cloudflare#1]
Hi, im trying to upload a string and get this error "ArgumentException: The request must be decorated with 'LazyUploadHttpWebRequestDecorator' in order to read the request stream. Arg_ParamName_Name" im new to net stuff

![image](https://user-images.githubusercontent.com/75300160/154861515-54e16111-5ef2-484a-9c50-650adc4f6759.png)

![image](https://user-images.githubusercontent.com/75300160/154861535-5e118756-a46b-4ea1-9d28-b1cab149e1a8.png)

**Comment by VordanN** [comment]
![image](https://user-images.githubusercontent.com/75300160/154861490-c854b1d8-7d17-4d67-bb61-acbbb8515948.png)

**Comment by gsemac** [comment]
Since the `ConnectStream` returned by `GetRequestStream()` doesn't support seeking, there's no way to access the POST data that was written to it in order to retry the request when the initial request fails due to Cloudflare. To get around this problem, I created `LazyUploadHttpWebRequestDecorator`, which stores the POST data in a seekable stream so that it can be re-sent.

The default `WebClientFactory` has a constructor taking an `IHttpWebRequestFactory`. Try registering a custom `IHttpWebRequestFactory` that looks like this:

```csharp
class CustomHttpWebRequestFactory :
    IHttpWebRequestFactory {

    public IHttpWebRequest Create(Uri requestUri) {

        return new LazyUploadHttpWebRequestDecorator(HttpWebRequestFactory.Default.Create(requestUri));

    }

}
```
